server:
  host: "0.0.0.0"
  port: 8080
  threads: 16

database:
  mariadb:
    host: "localhost"
    port: 3306
    username: "root"
    password: ""
    database: "chatroom"
    poolSize: 20

  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    poolSize: 20

logging:
  basename: "StarryChat"
  level: "info"  # trace, debug, info, warn, error, fatal
  rollSize: 67108864
  refreshInterval: 3 # minute
